version: "3"

networks:
  network1:
    driver: bridge

services:
  my_app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cont_app
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - bd
    networks:
      - network1
  bd:
    image: sql_base
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: cont_sql
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
       - MYSQL_ROOT_PASSWORD=1234
       - MYSQL_DATABASE=app_db
       - MYSQL_USER=app_user
       - MYSQL_PASSWORD=1234
    networks:
       - network1
volumes:
  db-data:

